### ISSUE TITLE
Add page for alliance selection

### ISSUE THREAD

**Issue by PatrickUbelhor** [Team2338/ScoutingServer#56]
Add a new page to help with alliance selection

- [ ] Only allow admins to view or edit
- [ ] Show 3 columns: list of available teams, pick list, and DNP
- [ ] Allow users to click-and-drag teams between lists
- [ ] Allow users to click-and-drag to reorder teams within a list
- [ ] Allow users to click on a team to see a modal with data, notes, and an image of the team
